### ISSUE TITLE
v2.0.0 Beta Testing

### ISSUE THREAD

**Issue by kevinschaich** [kevinschaich/mintable#55]
Version `2.x.x` represents an almost complete rewrite from the ground-up, expect it to be rough around the edges until we complete a few rounds of beta testing. Thanks for helping make Mintable better.

### What's New in `v2.0.0`

- **Complete (~4000 lines) rewrite:** Kept all the good stuff from `v1.x.x`, trimmed the fat where possible.
- **Migration to Typescript:** Easier to reason about correctness & establish rigid API constraints for integrations.
- **Migration Script:** Migrate your `v1.x.x` installation over in one command.
- **Simplified Install Process/Documentation:** Get up-and-running with Mintable in 3 commands.
- **Global `npm` package:** Call `mintable` as a command, anywhere on your machine without cloning anything.
- **`mintable` CLI/setup wizard:** Configure everything through an automated CLI-based setup wizard.
- **Config Validation:** Tells you the exact spot where your config is broken (if relevant).
- **Better Logging:** Almost every point of failure logs a human-readable error message.
- **Debug Mode:** Optionally log the results of every API request to debug strange behavior.
- **Error Reporting:** Click a single link which auto-fills an issue on GitHub with error/machine info.
- **Balances Sheet:** View the balances of all your accounts automatically on one sheet.
- **Per-Account Configuration:** Pull some accounts from Plaid, and others from a CSV (like Apple Card).
- **CSV Exporter:** Optionally export your results to a CSV file and use Excel/Numbers if you don't trust Google.
- Lots more

### What You've Helped Fix

- [x] [#67 Calling `updateConfig` with the `initialize` argument nukes existing config if it exists](https://github.com/kevinschaich/mintable/issues/67) – Fixed in #74 / `v2.0.0-beta.34`
- [x] [#70 Clicking 'link a new account' is showing me the success screen of my last authentication](https://github.com/kevinschaich/mintable/issues/70) – Fixed in #76 / `v2.0.0-beta.34`
- [x] [#73 mintable setup -> linking a new account successfully doesnt show the account](https://github.com/kevinschaich/mintable/issues/73) – Fixed in #76 / `v2.0.0-beta.34`
- [x] [#71 `mintable fetch` will not create new sheet tabs](https://github.com/kevinschaich/mintable/issues/71) – Fixed in #77 / `v2.0.0-beta.34`
- [x] [#49 Spreadsheet/CSV importer for banks not on Plaid](https://github.com/kevinschaich/mintable/issues/49) – Fixed in #80 / `v2.0.0-beta.34`
- [x] [#68 Accounts table is broken if you have not setup any accounts yet](https://github.com/kevinschaich/mintable/issues/68) – Fixed in #81 / `v2.0.0-beta.36`
- [x] [#81 Ability to delete accounts](https://github.com/kevinschaich/mintable/issues/81) – Fixed in #81 / `v2.0.0-beta.36`
- [x] [#69 Sheets are not getting sorted correctly](https://github.com/kevinschaich/mintable/issues/69) – Fixed in ac3fb91edd3017d1b406e7c88f9a9c87f7baccef / `v2.0.0-beta.39`
- [x] [GitHub Actions Integration](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-the-cloud--via-github-actions) – Fixed in `v2.0.0-beta.40`
- [x] [BitBar Integration](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-your-macs-menu-bar--via-bitbar) – Fixed in `v2.0.0-beta.40`
- [x] [`cron` Integration](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-your-local-machines-terminal--via-cron) – Fixed in `v2.0.0-beta.40`
- [x] [#50 Export to CSV option (instead of Google Sheets)](https://github.com/kevinschaich/mintable/issues/50) – Fixed in #80 / `v2.0.0-beta.41`
- [x] [#57 Transaction Overrides](https://github.com/kevinschaich/mintable/issues/57) – Added in #96 / `v2.0.0-beta.44`
- [x] [#58 Transaction Filters](https://github.com/kevinschaich/mintable/issues/58) – Added in #96 / `v2.0.0-beta.44`

### Testing Instructions

I've compiled a **Testing Checklist** below if you have the time, but if you don't want to start from scratch, I'd still appreciate any feedback.

Please [report an Issue](https://github.com/kevinschaich/mintable/issues/new?title=Bug:%20v2.0.0%20Beta%20-%20[brief%20issue%20description%20here]) for anything _not_ listed above which seems like a regression/bug and apply the `Bug: v2.0.0 Beta` label. If you encounter any issues with these instructions themselves or have any general feedback, please leave a comment below.

### Testing Checklist

- [x] Make a backup copy of your `v1.x.x` `mintable.config.json`.
- [x] [Install Mintable `v2.x.x` and migrate your `v1.x.x` config](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#migrating-from-v1xx).
- [x] [Create a new blank Google Sheet](https://sheets.new).
- [x] _Optional_ If you set a template sheet in your `v1.x.x` config, create a tab with that title
- [x] Change the `integrations.google.documentId` property in `~/mintable.jsonc` to the blank one you just created.
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).
- [x] Delete `~/mintable.jsonc`.
- [x] [Use the setup wizard to configure Google Sheets and Plaid](https://github.com/kevinschaich/mintable/tree/release/2.0.0#quickstart).
- [x] [Add a new account](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#addingupdating-accounts).
- [x] [Refresh the credentials for an existing account](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#addingupdating-accounts).
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).
- [x] Make a backup copy of your _production_ Google Sheet.
- [x] Change the `integrations.google.documentId` property in `~/mintable.jsonc` to the new backup sheet you just made.
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).

**Comment by dflock** [comment]
Sign me up!

**Comment by yawhide** [comment]
same here

**Comment by eliluong** [comment]
Hi, I'm interested in testing out v2.0.0. I've recently set up mintable, trying to see what I can do with it. Thanks.

**Comment by kev1nnsays** [comment]
Would love to try it out.

**Comment by pickettd** [comment]
I'm interested to try!

**Comment by thomastraum** [comment]
yes!

**Comment by mrginogit** [comment]
Sign me up!

**Comment by nboley2** [comment]
I'm in! Sign me up!

**Comment by kevinschaich** [comment]
@dflock @yawhide @eliluong @kev1nnsays @pickettd @mspych @thomastraum @mrginogit @nboley2 @willie – Thank you for your incredible patience here. Today is the day.

I've [updated the issue description](https://github.com/kevinschaich/mintable/issues/55#issue-598323572) with instructions on how you can help test `v2.0.0`. Happy testing – and thank you so much for helping make Mintable better.

**Comment by kevinschaich** [comment]
All – thanks so much for your help testing so far! Along with a number of bug fixes, excited to announce two new features in `v2.0.0-beta.34`:

- [Import Transactions via a CSV / bank statement](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#manually--on-your-local-machine--via-csv-bank-statements)
- A library of [banking institution statement templates](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs/templates) for people who don't want to use Plaid, including [Apple Card](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/templates/apple-card.json)
- [Automate Mintable in your Mac's Menu Bar using BitBar](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-your-macs-menu-bar--via-bitbar) (GitHub Actions coming soon)

Keen to hear your thoughts on these! Thanks again 😄

**Comment by yawhide** [comment]
>     * [Import Transactions via a CSV / bank statement](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#manually--on-your-local-machine--via-csv-bank-statements)
> 
>     * A library of [banking institution statement templates](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs/templates) for people who don't want to use Plaid, including [Apple Card](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/templates/apple-card.json)

are you hoping to have a community build list of templates?

**Comment by mrginogit** [comment]
Finally got some time to run through this. Great stuff! A few observations as I went through the test plan:

- Following the install/migrate steps, it took me a second to realize it installs globally, and my jsonc file ended up in my Windows user folder.  It may be good to mention this parameter in the migration instructions too:
`[INFO] You can supply either --config-file or --config-variable to specify a different configuration.`
- Transactions updated successfully
- If we delete mintable.jsonc to start fresh and re-add our accounts, does that mean all of our accounts will look new to Plaid and decrement from our 100 allowed accounts limit (if using a free account)?

**Comment by yawhide** [comment]
> If we delete mintable.jsonc to start fresh and re-add our accounts, does
that mean all of our accounts will look new to Plaid and decrement from our
100 allowed accounts limit (if using a free account)?

Yes

**Comment by kevinschaich** [comment]
@yawhide, answers below:

> are you hoping to have a community build list of templates?

That's hopefully the plan. I will add templates for the ~5 or so banking institutions which I use personally, but this will be a lot more valuable as a crowdsourced effort.

> Also in the templates, is there a way to specify if the banking institution's transactions are in usd or cad?

Not currently. Happy to consider it as a feature request or approve a PR but probably won't be prioritized for the `2.0.0` release for now.

**Comment by eliluong** [comment]
@kevinschaich Can you consider a template/plugin for importing data from Personal Capital? At this time mintable can only import data that exists in the institution's 'database' and most have limited it to only the most recent year or so. Thanks.

**Comment by kevinschaich** [comment]
@eliluong I don't use Personal Capital so I wouldn't be able to build/test the integration there, but definitely encourage you to try following the instructions here:

[Import Transactions via a CSV / bank statement](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#manually--on-your-local-machine--via-csv-bank-statements)

Basically – if Personal Capital supports CSV exports – you're set. There is a CLI setup wizard in the link above to get you started and then you'd need to define a mapping from PC's output columns to Mintable's input columns.

Happy to support you if you encounter any issues, and please share your config as a template if you do get it working! 😄

**Comment by kevinschaich** [comment]
Hey everyone, another exciting update – as of today, #80, `v2.0.0-beta.40` – all the features scheduled for the `v2.0.0` release are complete, and we've fixed all the bugs reported so far! 🎉 

A few more new features I'm excited to announce:

- A Growing CSV Import [Templates Library](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs/templates) (thanks @yawhide + @Zeustopher for your contributions! ❤️)
- [Export to CSV](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#on-your-local-machine--via-csv-files) for both account balances & transactions
- [GitHub Actions Integration](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-the-cloud--via-github-actions)
- [`cron` Integration / Documentation](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#automatically-in-your-local-machines-terminal--via-cron)

Test away and hit me with your feedback!

**Comment by kevinschaich** [comment]
Hey all, happy to announce that `v2.x.x` now also has the capability to filter or modify your transactions on-the-fly (a hotly requested feature from `v1.x.x`)!

Check it out:

- [Transaction `filter` Rules](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#transaction-filter-rules)
- [Transaction `override` Rules](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#transaction-override-rules)

**Comment by kevinschaich** [comment]
@dflock @yawhide @eliluong @kev1nnsays @pickettd @mspych @thomastraum @mrginogit @nboley2 @willie – Hey all! 

Apologies for the @ spam – I wanted to make sure this reaches you guys before the masses. Barring any DEFCON-5 issues, I think we can shoot for the beginning of August for a tentative release date. Wanted to ask you guys to read through the conversation above and if you haven't already, test out whatever you have time for:

* [Testing checklist](https://github.com/kevinschaich/mintable/issues/55#issue-598323572) above
* Additional features mentioned in my subsequent comments above

Let me know what's broken, what's not intuitive, and what's not documented well. I hope we can make the 2.x.x a great release and pain-free upgrade for everybody.

Thank you so much for your continued contributions to make personal finance more accessible to our community! 😄

**Comment by kevinschaich** [comment]
# [Mintable `v2.0.1` 🎉](https://github.com/kevinschaich/mintable/releases/tag/2.0.1)

Thanks so much for all your help!

**Comment by thomastraum** [comment]
Congrats!

— ✌ Thomas Traum — TRAUM INC — Creative Director — thomas@trauminc.com— +44 (0)79 121 60 200
