### ISSUE TITLE
[v2.0.0] Test Report: @kevinschaich

### ISSUE THREAD

**Issue by kevinschaich** [kevinschaich/mintable#64]
All, thanks for your incredible patience here. Today is the day.

Version `2.x.x` represents an almost complete rewrite from the ground-up, expect it to be rough around the edges until we complete a few rounds of beta testing. Thanks for helping make Mintable better.

### What's New in `v2.0.0`

- **Complete (~4000 lines) rewrite:** Kept all the good stuff from `v1.x.x`, trimmed the fat where possible.
- **Migration to Typescript:** Easier to reason about correctness & establish rigid API constraints for integrations.
- **Migration Script:** Migrate your `v1.x.x` installation over in one command.
- **Simplified Install Process/Documentation:** Get up-and-running with Mintable in 3 commands.
- **Global `npm` package:** Call `mintable` as a command, anywhere on your machine without cloning anything.
- **`mintable` CLI/setup wizard:** Configure everything through an automated CLI-based setup wizard.
- **Config Validation:** Tells you the exact spot where your config is broken (if relevant).
- **Better Logging:** Almost every point of failure logs a human-readable error message.
- **Debug Mode:** Optionally log the results of every API request to debug strange behavior.
- **Error Reporting:** Click a single link which auto-fills an issue on GitHub with error/machine info.
- **Balances Sheet:** View the balances of all your accounts automatically on one sheet.
- **Per-Account Configuration:** Pull some accounts from Plaid, and others from a CSV (like Apple Card).
- **CSV Exporter:** Optionally export your results to a CSV file and use Excel/Numbers if you don't trust Google.
- Lots more

### What's Not Working Yet

- [ ] [#69 Sheets are not getting sorted correctly](https://github.com/kevinschaich/mintable/issues/69)
- [ ] [#68 Accounts table is broken if you have not setup any accounts yet](https://github.com/kevinschaich/mintable/issues/68)
- [ ] [#67 Calling `updateConfig` with the `initialize` argument nukes existing config if it exists](https://github.com/kevinschaich/mintable/issues/67)
- [ ] [#50 Export to CSV option (instead of Google Sheets)](https://github.com/kevinschaich/mintable/issues/50)
- [ ] [#49 Spreadsheet/CSV importer for banks not on Plaid](https://github.com/kevinschaich/mintable/issues/49)
- [ ] [#46 Add a test suite](https://github.com/kevinschaich/mintable/issues/46)
- [ ] [#57 Transaction Overrides](https://github.com/kevinschaich/mintable/issues/57)
- [ ] [#58 Transaction Filters](https://github.com/kevinschaich/mintable/issues/58)
- [ ] Probably lots more

### Testing Instructions

I've compiled a **Testing Checklist** below if you have the time, but if you don't want to start from scratch, I'd still appreciate any feedback.

Please [report an Issue](https://github.com/kevinschaich/mintable/issues/new?title=Bug:%20v2.0.0%20Beta%20-%20[brief%20issue%20description%20here]) for anything _not_ listed above which seems like a regression/bug and apply the `Bug: v2.0.0 Beta` label. If you encounter any issues with these instructions themselves or have any general feedback, please leave a comment below.

### Testing Checklist

- [x] Make a backup copy of your `v1.x.x` `mintable.config.json`.
- [x] [Install Mintable `v2.x.x` and migrate your `v1.x.x` config](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#migrating-from-v1xx).
- [x] [Create a new blank Google Sheet](https://sheets.new).
- [x] Change the `integrations.google.documentId` property in `~/mintable.jsonc` to the blank one you just created.
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).
- [x] Delete `~/mintable.jsonc`.
- [x] [Use the setup wizard to configure Google Sheets and Plaid](https://github.com/kevinschaich/mintable/tree/release/2.0.0#quickstart).
- [x] [Add a new account](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#addingupdating-accounts).
- [x] [Refresh the credentials for an existing account](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#addingupdating-accounts).
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).
- [x] Make a backup copy of your _production_ Google Sheet.
- [x] Change the `integrations.google.documentId` property in `~/mintable.jsonc` to the new backup sheet you just made.
- [x] [Update your transactions](https://github.com/kevinschaich/mintable/blob/release/2.0.0/docs/README.md#updating-transactionsaccounts).
